---
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'scripts/**/*'
    - 'scripts/*'
    - 'script/**/*'
    - 'one-time/**/*'
    - 'one-timer/**/*'
    - 'one-timers/**/*'
    - 'db/**/*'
    - 'config.ru'
    - 'Rakefile'
    - 'lib/templates/**/*'
    - 'vender/**/*'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
Style/GuardClause:
  MinBodyLength: 1
  Enabled: false
Style/AndOr:
  Enabled: false
  EnforcedStyle: conditionals
Style/PercentLiteralDelimiters:
  PreferredDelimiters: {}
  Enabled: false
Style/Alias:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/FrozenStringLiteralComment:
  Enabled: false
# class Admin::PageController
Style/ClassAndModuleChildren:
  Enabled: false

# asddsa == 0  -> asddsa.zero?
Style/NumericPredicate:
  Enabled: false
# ->() {}  -- lambda {|a| }
Style/Lambda:
  EnforcedStyle: 'literal'
# if bla.nil?  --  if bla == nil
Style/NilComparison:
  Enabled: false
# Ruby 3
Style/FrozenStringLiteralComment:
  Enabled: false
# def bla; end
Style/EmptyMethod:
  Enabled: false
# [ "700", "200" ] -> %w[w w]
Style/WordArray:
  Enabled: false
# RSpec nervt
Metrics/BlockLength:
  ExcludedMethods: ['task', 'namespace', 'get', 'post', 'describe', 'context', 'specify', 'it', 'route_param', 'draw', 'register', 'register_page', 'controller', 'included', 'params', 'resource', 'with_options', 'use_cassette', 'configure']
Bundler/OrderedGems:
  Enabled: false
# update_all, update_column
# set_ und get_ verbote
Naming/AccessorMethodName:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/AsciiComments:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
Style/NonNilCheck:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
